apiVersion: v2
name: gitlab
description: gitlab Argo demo
type: application
version: 0.1.0
appVersion: 5.0.2

dependencies:
- name: gitlab
  version: 4.12.1
  repository: https://charts.gitlab.io/

gitlab:
  global:
    common:
      labels: 
        johnny: test
